<?php

namespace Common\PHPUnit;

use Think\Log;

class BaseTest extends \PHPUnit_Framework_TestCase
{
    protected static $app = null;

    protected static $gardenId = 0;
    protected static $garden = [];
    protected static $admin = [];

    static public function setupBeforeClass()
    {
        error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING);
        date_default_timezone_set('Asia/Shanghai');
        // 下面四行代码模拟出一个应用实例, 每一行都很关键, 需正确设置参数
        $appPath = realpath(__DIR__ . '/../../../') . '/App/';
        $thinkPath = realpath(__DIR__ . '/../../../Include') . '/';
        self::$app = new \Think\PhpunitHelper($appPath, $thinkPath);
        self::$app->setMVC('hyg.w6g.com', 'AppManage', 'Public');

        $globalPath = realpath(APP_PATH . '../GLOBAL') . '/global.php';
        $content = file_get_contents($globalPath);
        preg_match_all('/define.*[\'"](\w+)[\'"].*((?<=[\'"]).+(?=[\'"])|true|false)/im',$content,$matches,PREG_SET_ORDER);
        $currentMode = 'home_dev';
        foreach ($matches as $data) {
            if ($data[1] === 'MODE') {
                $currentMode = $data[2];
                break;
            }
        }
        switch ($currentMode) {
            case 'home_common':
                $config = [
                    'DB_TYPE' => 'mysql',
                    'DB_HOST' => '129.226.148.177',
                    'DB_PORT' => '3306',
                    'DB_USER' => 'ycyg',
                    'DB_PWD' => 'LykDJJnBDJbKA62m',
                    'DB_NAME' => 'ycyg_db',
                    'DB_PREFIX' => 'wjd_',
                    'DB_CHARSET' => 'utf8',
                    'DATA_CACHE_PREFIX' => 'YCYG_',//缓存前缀
                    'REDIS_HOST' => '127.0.0.1', //redis服务器ip，多台用逗号隔开；读写分离开启时，第一台负责写，其它[随机]负责读；
                    'REDIS_PORT' => '6379',//端口号
                    'DATA_CACHE_TIMEOUT' => '300',//超时时间
                    'REDIS_PERSISTENT' => false,//是否长连接 false=短连接
                    'REDIS_AUTH' => '',//AUTH认证密码
                ];
                break;
            default:
                $config = [
                    'DB_TYPE' => 'mysql',
                    'DB_HOST' => '123.207.98.106',
                    'DB_PORT' => '3306',
                    'DB_USER' => 'admin',
                    'DB_PWD' => '9ewFk02t5QfXA8W2',
                    'DB_NAME' => 'tgmall_db',
                    'DB_PREFIX' => 'wjd_',
                    'DB_CHARSET' => 'utf8',
                    'DATA_CACHE_PREFIX' => 'TG_',//缓存前缀
                    'REDIS_HOST' => '123.207.98.106', //redis服务器ip，多台用逗号隔开；读写分离开启时，第一台负责写，其它[随机]负责读；
                    'REDIS_PORT' => '6379',//端口号
                    'DATA_CACHE_TIMEOUT' => '300',//超时时间
                    'REDIS_PERSISTENT' => false,//是否长连接 false=短连接
                    'REDIS_AUTH' => 'xunxin8988998',//AUTH认证密码
                ];
                break;
        }
        $config['DB_CACHE_ON'] = false;

        self::$app->setTestConfig($config); // 一定要设置一个测试用的数据库,避免测试过程破坏生产数据
        self::$app->start();
    }

    public static function tearDownAfterClass()
    {
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }
}