<?php
/**
 * Created by PhpStorm.
 * User: hjun
 * Date: 2018/4/29
 * Time: 15:16
 */

namespace Common\Service;

use Common\Model\GardenModel;
use Common\PHPUnit\BaseTest;

class GardenServiceTest extends BaseTest
{

    /**
     * @var GardenService
     */
    protected $gardenService;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->gardenService = new GardenService();
    }

    public function testStopById()
    {

    }

    public function testStartById()
    {

    }

    public function testInsert()
    {
        $gardenModel = new GardenModel();
        $this->gardenService->insert($gardenModel);
    }

    public function testGetList()
    {

    }

    public function testUpdate()
    {

    }

    public function testGetEachStatusNum()
    {

    }
}
