<?php

namespace Common\PHPUnit\Room;

class BaseTest extends \PHPUnit_Framework_TestCase
{
    protected static $app = null;

    protected static $gardenId = 0;
    protected static $garden = [];
    protected static $admin = [];

    static public function setupBeforeClass()
    {
        error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING);
        date_default_timezone_set('Asia/Shanghai');
        // 下面四行代码模拟出一个应用实例, 每一行都很关键, 需正确设置参数
        self::$app = new \Think\PhpunitHelper();
        self::$app->setMVC('hyg.w6g.com', 'Super', 'Test');
        $config = [
            'DB_TYPE' => 'mysql',
            'DB_HOST' => '123.207.98.106',
            'DB_PORT' => '3306',
            'DB_USER' => 'pims',
            'DB_PWD' => 'pims8988998',
            'DB_NAME' => 'pims_db',
            'DB_PREFIX' => 'wjd_',
            'DB_CHARSET' => 'utf8',
        ];
        self::$app->setTestConfig($config); // 一定要设置一个测试用的数据库,避免测试过程破坏生产数据
        self::$app->start();
    }

    public static function tearDownAfterClass()
    {
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }

    public function getTestData($name)
    {
        $data = file_get_contents("testData/{$name}.json");
        $data = json_decode($data, 1);
        return empty($data) ? [] : $data;
    }
}